version: '3.8'

services:
  web:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - api
  api:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production