version: '3.8'

services:
  web:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    commnand: npm run dev -- --host
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "5173:5173"
    depends_on:
      - api
  api:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production